"""Train (or compile) -> intervene -> metrics.json -> web/src/metrics.gen.ts.

CLI: python scripts/run.py
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from circuits import const
from circuits.eval import evaluate_circuit, evaluate_trained, print_report, write_metrics
from circuits.model import HAS_TORCH

METRICS_GEN = "web/src/metrics.gen.ts"


def write_data_ts(m: dict):
    if not os.path.exists("web/src"):
        return
    sweep = m.get("sweep") or []
    joint = m.get("joint") or []
    named = [[int(a), int(b)] for a, b in m.get("named_heads", [])]
    arch = [
        {
            "layer": int(r["layer"]),
            "head": int(r["head"]),
            "drop": float(r["drop"]),
            "ablatePct": float(r["ablate_pct"]),
            "named": [int(r["layer"]), int(r["head"])] in named,
        }
        for r in sweep
    ]
    body = f"""// Generated by scripts/run.py. Numbers match metrics.json. Do not hand-edit.

export const ILLUSTRATIVE = {str(bool(m.get('illustrative'))).lower()}

export const PROTOCOL = {{
  task: 'induction copy',
  vocab: {int(m['vocab'])},
  seqLen: {int(m['seq_len'])},
  nLayers: {int(m['n_layers'])},
  nHeads: {int(m['n_heads'])},
  nEval: {int(m['n_eval'])},
  namedHeads: {json.dumps(named)},
}}

export const METRICS = {{
  successPct: {float(m['success_pct'])},
  taskPct: {float(m['task_pct'])},
  randomPct: {float(m['random_intervention_pct'])},
  chancePct: {float(m['chance_pct'])},
  interventionPct: {float(m['intervention_pct'])},
}}

export const ARCH: {{ layer: number; head: number; drop: number; ablatePct: number; named: boolean }}[] = {json.dumps(arch)}

export const JOINT: {{ n: number; drop: number; ablatePct: number }}[] = {json.dumps([{"n": int(j["n"]), "drop": float(j["drop"]), "ablatePct": float(j["ablate_pct"])} for j in joint])}

export const ABLATION = [
  {{ model: 'named', successPct: {float(m['success_pct'])}, label: 'Locked named-head interventions' }},
  {{ model: 'random', successPct: {float(m['random_intervention_pct'])}, label: 'Random-head interventions' }},
  {{ model: 'chance', successPct: {float(m['chance_pct'])}, label: 'Chance (1 / vocab)' }},
]
"""
    with open(METRICS_GEN, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"wrote {METRICS_GEN}")


def main():
    if not HAS_TORCH:
        m = evaluate_circuit()
        m["illustrative"] = True
        m["blocker"] = "torch unavailable"
        m["source"] = "circuit"
        write_metrics(m)
        print_report(m)
        print("ILLUSTRATIVE")
        print("BLOCKER:", m["blocker"])
        write_data_ts(m)
        return

    m = evaluate_trained()
    if m["success_pct"] < 85 or m["task_pct"] < 85:
        c = evaluate_circuit()
        c["adr"] = (
            "trained net missed the intervention floor; "
            "headline is the locked compiled copy circuit on the same task"
        )
        c["train_note"] = m.get("train_note")
        c["trained_success_pct"] = m["success_pct"]
        c["trained_task_pct"] = m["task_pct"]
        c["source"] = "circuit"
        m = c

    if m["n_eval"] > const.MAX_EVAL:
        sys.exit(f"HARD FAIL: n_eval {m['n_eval']} over cap {const.MAX_EVAL}")

    write_metrics(m)
    print_report(m)
    if m.get("adr"):
        print("ADR:", m["adr"])
    if m.get("illustrative"):
        print("ILLUSTRATIVE")
        print("BLOCKER:", m.get("blocker", ""))
    write_data_ts(m)


if __name__ == "__main__":
    main()
