// Generated by scripts/run.py. Numbers match metrics.json. Do not hand-edit.

export const ILLUSTRATIVE = false

export const PROTOCOL = {
  task: 'induction copy',
  vocab: 16,
  seqLen: 4,
  nLayers: 1,
  nHeads: 4,
  nEval: 256,
  namedHeads: [[0, 0], [0, 1], [0, 2]],
}

export const METRICS = {
  successPct: 100.0,
  taskPct: 100.0,
  randomPct: 0.0,
  chancePct: 6.25,
  interventionPct: 100.0,
}

export const ARCH: { layer: number; head: number; drop: number; ablatePct: number; named: boolean }[] = [{"layer": 0, "head": 0, "drop": 0.0, "ablatePct": 100.0, "named": true}, {"layer": 0, "head": 1, "drop": 0.0, "ablatePct": 100.0, "named": true}, {"layer": 0, "head": 2, "drop": 0.0, "ablatePct": 100.0, "named": true}, {"layer": 0, "head": 3, "drop": 0.0, "ablatePct": 100.0, "named": false}]

export const JOINT: { n: number; drop: number; ablatePct: number }[] = [{"n": 1, "drop": 0.0, "ablatePct": 100.0}, {"n": 2, "drop": 0.7812, "ablatePct": 99.2188}, {"n": 3, "drop": 33.2031, "ablatePct": 66.7969}, {"n": 4, "drop": 95.3125, "ablatePct": 4.6875}]

export const ABLATION = [
  { model: 'named', successPct: 100.0, label: 'Locked named-head interventions' },
  { model: 'random', successPct: 0.0, label: 'Random-head interventions' },
  { model: 'chance', successPct: 6.25, label: 'Chance (1 / vocab)' },
]
